### ISSUE TITLE
JsonRPCClient constructor is missing the $proxy parameter

### ISSUE THREAD

**Issue by cavo789** [weberhofer/jsonrpcphp#6]
Hello

I've notice that you're using a $proxy parameter in your constructor but that parameter isn't defined in your function:

https://github.com/weberhofer/jsonrpcphp/blob/master/src/org/jsonrpcphp/JsonRPCClient.php#L72-L88

The correct code, I think, has to be:

```php
     /**
     * Takes the connection parameters.
     *
     * @param string $url
     * @param bool   $debug
     * @param mixed  $proxy
     */
    public function __construct($url, $debug = false, $proxy = '')
    {
        // server URL
        $this->url = $url;
        // proxy
        empty($proxy) ? $this->proxy = '' : $this->proxy = $proxy;
		// debug state
        empty($debug) ? $this->debug = false : $this->debug = true;
        // message id
        $this->id = 1;
    }
```

I've tried to create a new branch and to push a Pull request but I don't have the permission to do this. Perhaps something to change in the settings of your current repo.

Thanks!

**Comment by cavo789** [comment]
Forgot to also mention that the `__call` function should also be updated to add these lines:

```php
if ('' !== trim($this->proxy)) {
    curl_setopt($ch, CURLOPT_PROXY, $this->proxy);
}
```

**Comment by weberhofer** [comment]
Thanks @cavo789 for notifying me. I have fixed the code. Btw: Before you do changes you like to submit you have to fork the project.

**Comment by cavo789** [comment]
Hello.

Thanks for the update.

For the fork, I had tried to create a fork but unless I was mistaken; this was not possible at that time (maybe you had forbidden the creation of a fork and the submission of a PR?)

Have a nice evening.

**Comment by weberhofer** [comment]
@cavo789, there is nothing special on that repo. You definitely should be able to fork except there is/was something wrong at github.
